const path = {
  PUBLIC: "/",
  HOME: "trang-chu",
  ALL: "*",
  LOGIN: "login",
  PRODUCTS: "san-pham",
  PRODUCTS_CATEGORY: ":category",
  DETAIL_PRODUCT_CATEGORY_PID: ":category/:pid",
  BLOG: "tin-tuc",
  DETAIL_BLOG_CATEGORY_BID: "tin-tuc/:bid",
  SERVICE: "service",
  ABOUT_US: "ve-chung-toi",
  FAQ: "faq",
  CONTACT: "lien-he",
  DETAIL_CART: "my-cart",
  CHECKOUT: "checkout",

  //admin
  ADMIN: "admin",
  DASHBOARD: "dashboard",
  MANAGE_USER: "manage-user",
  MANAGE_ORDER: "manage-order",
  MANAGE_PRODUCT: "manage-product",
  MANAGE_PRODUCT_VARIANTS: "manage-product-variants",
  CREATE_PRODUCT: "create-product",
  MANAGE_CATEGORY_PRODUCT: "manage-category-product",
  CREATE_CATEGORY_PRODUCT: "create-category-product",
  MANAGE_BLOG: "manage-blog",
  CREATE_BLOG: "create-blog",
  MANAGE_CATEGORY_BLOG: "manage-category-blog",
  CREATE_CATEGORY_BLOG: "create-category-blog",
  MANAGE_COLOR: "manage-color",
  CREATE_COLOR: "create-color",
  MANAGE_ENQUIRY: "manage-enquiry",
  CREATE_CONFIG: "create-config",
  CREATE_MENU: "create-menu",
  MANAGE_COUPON: "manage-coupon",
  CREATE_COUPON: "create-coupon",
  PERSONAL_ADMIN: "personal-admin",
  MANAGE_SHIP: "manage-ship",
  CREATE_SHIP: "create-ship",
  MANAGE_BRAND: "manage-brand",
  CREATE_BRAND: "create-brand",
  MANAGE_RETAIL: "manage-retail",
  CREATE_RETAIL: "create-retail",
  //member
  MEMBER: "member",
  PERSONAL: "personal",
  MY_CART: "my-cart",
  HISTORY: "buy-history",
  WISHLIST: "wishlist",
};

export default path;
